// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseAvatar: typeof import('./../src/components/BaseAvatar/index.vue')['default']
    BaseBrand: typeof import('./../src/components/BaseBrand/index.vue')['default']
    BaseButtonGroup: typeof import('./../src/components/BaseButtonGroup/index.vue')['default']
    BaseCard: typeof import('./../src/components/BaseCard/index.vue')['default']
    BaseCollapse: typeof import('./../src/components/BaseCollapse/index.vue')['default']
    BaseContextmenu: typeof import('./../src/components/BaseContextmenu/index.vue')['default']
    BaseDrawer: typeof import('./../src/components/BaseDrawer/index.vue')['default']
    BaseForm: typeof import('./../src/components/BaseForm/index.vue')['default']
    BaseFormComponentsColorPicker: typeof import('./../src/components/BaseForm/components/ColorPicker/index.vue')['default']
    BaseFormComponentsMapPicker: typeof import('./../src/components/BaseForm/components/MapPicker/index.vue')['default']
    BaseFormComponentsMapPickerComponentsPickerModal: typeof import('./../src/components/BaseForm/components/MapPicker/components/PickerModal.vue')['default']
    BaseFormComponentsMapPickerComponentsPickerTrigger: typeof import('./../src/components/BaseForm/components/MapPicker/components/PickerTrigger.vue')['default']
    BaseFormComponentsUserPicker: typeof import('./../src/components/BaseForm/components/UserPicker/index.vue')['default']
    BaseMap: typeof import('./../src/components/BaseMap/index.vue')['default']
    BaseMapComponentsControlControlCoordPicker: typeof import('./../src/components/BaseMap/components/Control/ControlCoordPicker.vue')['default']
    BaseMapComponentsControlControlLayer: typeof import('./../src/components/BaseMap/components/Control/ControlLayer.vue')['default']
    BaseMapComponentsControlControlTile: typeof import('./../src/components/BaseMap/components/Control/ControlTile.vue')['default']
    BaseMapComponentsMarkerCarMarker: typeof import('./../src/components/BaseMap/components/Marker/CarMarker.vue')['default']
    BaseMapComponentsMarkerUserMarker: typeof import('./../src/components/BaseMap/components/Marker/UserMarker.vue')['default']
    BaseModal: typeof import('./../src/components/BaseModal/index.vue')['default']
    BaseTable: typeof import('./../src/components/BaseTable/index.vue')['default']
    BaseTableFilter: typeof import('./../src/components/BaseTableFilter/index.vue')['default']
    BaseUserCard: typeof import('./../src/components/BaseUserCard/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
