<template>
  <BaseTablePro
    ref="table"
    title="报表管理列表"
    selection="checkbox"
    :service="service"
    :table-columns="tableColumns"
    :table-filter="tableFilter"
    :table-operates="tableOperates"
  />
</template>
<script setup lang="tsx">
import { BaseTablePro, useTableMethods } from '@/components/BaseTable'
import { Link, Space } from '@arco-design/web-vue'
// import { createBaseModal } from '@/components/BaseModal'
// import ReportEditor from './src/ReportEditor/index.vue'

function mockResponse<T>(data: T) {
  return new Promise<T>((resolve) => {
    setTimeout(() => resolve(data), 500)
  })
}

const { table, refresh } = useTableMethods()

const service = () =>
  mockResponse({
    endRow: 10,
    firstPage: 1,
    hasNextPage: true,
    hasPreviousPage: false,
    isFirstPage: true,
    isLastPage: false,
    lastPage: 8,
    list: [
      {
        componentId: null,
        componentName: '钢结构物',
        createTime: null,
        firstWarningLower: -10000,
        firstWarningUpper: 10000,
        handlerTime: null,
        handlerUserId: null,
        id: 898816,
        level: 1,
        machineId: null,
        measures: null,
        modifyTime: null,
        secondWarningLower: -8000,
        secondWarningUpper: 8000,
        sendMessage: null,
        sensorCoding: 'C1802191467',
        sensorDetailsId: 2,
        sensorId: 2198,
        sensorName: 'SX-3应变',
        sensorTypeName: '应变传感器',
        status: 0,
        structureId: 2139,
        structureName: '漳州芝山大桥',
        thirdWarningLower: -6000,
        thirdWarningUpper: 6000,
        unit: 'με',
        username: null,
        value: -14721.578,
        warningInterval: 1,
        warningTime: '2024-02-05 14:09:49',
      },
      {
        componentId: null,
        componentName: '钢结构物',
        createTime: null,
        firstWarningLower: -10000,
        firstWarningUpper: 10000,
        handlerTime: null,
        handlerUserId: null,
        id: 898817,
        level: 1,
        machineId: null,
        measures: null,
        modifyTime: null,
        secondWarningLower: -8000,
        secondWarningUpper: 8000,
        sendMessage: null,
        sensorCoding: 'C1802191470',
        sensorDetailsId: 2,
        sensorId: 2200,
        sensorName: 'SX-5应变',
        sensorTypeName: '应变传感器',
        status: 0,
        structureId: 2139,
        structureName: '漳州芝山大桥',
        thirdWarningLower: -6000,
        thirdWarningUpper: 6000,
        unit: 'με',
        username: null,
        value: -14231.23,
        warningInterval: 1,
        warningTime: '2024-02-05 14:09:49',
      },
      {
        componentId: null,
        componentName: '桥面铺装',
        createTime: null,
        firstWarningLower: -2,
        firstWarningUpper: 100000,
        handlerTime: null,
        handlerUserId: null,
        id: 898815,
        level: 3,
        machineId: null,
        measures: null,
        modifyTime: null,
        secondWarningLower: -1,
        secondWarningUpper: 80000,
        sendMessage: null,
        sensorCoding: 'C222201',
        sensorDetailsId: 7,
        sensorId: 1623,
        sensorName: '火车站-市区 车道1',
        sensorTypeName: '称重传感器',
        status: 0,
        structureId: 1578,
        structureName: '台江大桥',
        thirdWarningLower: 0,
        thirdWarningUpper: 50000,
        unit: 't',
        username: null,
        value: 55640,
        warningInterval: 1,
        warningTime: '2024-02-05 05:47:34',
      },
      {
        componentId: null,
        componentName: '桥面铺装',
        createTime: null,
        firstWarningLower: -2,
        firstWarningUpper: 100000,
        handlerTime: null,
        handlerUserId: null,
        id: 898814,
        level: 3,
        machineId: null,
        measures: null,
        modifyTime: null,
        secondWarningLower: -1,
        secondWarningUpper: 80000,
        sendMessage: null,
        sensorCoding: 'C222202',
        sensorDetailsId: 7,
        sensorId: 1624,
        sensorName: '火车站-市区 车道2',
        sensorTypeName: '称重传感器',
        status: 0,
        structureId: 1578,
        structureName: '台江大桥',
        thirdWarningLower: 0,
        thirdWarningUpper: 50000,
        unit: 't',
        username: null,
        value: 61650,
        warningInterval: 1,
        warningTime: '2024-02-05 05:16:55',
      },
      {
        componentId: null,
        componentName: '桥面铺装',
        createTime: null,
        firstWarningLower: -2,
        firstWarningUpper: 100000,
        handlerTime: null,
        handlerUserId: null,
        id: 898813,
        level: 3,
        machineId: null,
        measures: null,
        modifyTime: null,
        secondWarningLower: -1,
        secondWarningUpper: 80000,
        sendMessage: null,
        sensorCoding: 'C222201',
        sensorDetailsId: 7,
        sensorId: 1623,
        sensorName: '火车站-市区 车道1',
        sensorTypeName: '称重传感器',
        status: 0,
        structureId: 1578,
        structureName: '台江大桥',
        thirdWarningLower: 0,
        thirdWarningUpper: 50000,
        unit: 't',
        username: null,
        value: 64960,
        warningInterval: 1,
        warningTime: '2024-02-05 04:35:42',
      },
      {
        componentId: null,
        componentName: '钢结构物',
        createTime: null,
        firstWarningLower: -1000,
        firstWarningUpper: 1000,
        handlerTime: null,
        handlerUserId: null,
        id: 898812,
        level: 3,
        machineId: null,
        measures: null,
        modifyTime: null,
        secondWarningLower: -800,
        secondWarningUpper: 900,
        sendMessage: null,
        sensorCoding: 'C1906010923',
        sensorDetailsId: 1,
        sensorId: 1651,
        sensorName: '桥塔左侧中心',
        sensorTypeName: '加速度传感器',
        status: 0,
        structureId: 1578,
        structureName: '台江大桥',
        thirdWarningLower: -600,
        thirdWarningUpper: 800,
        unit: 'mm/s2',
        username: null,
        value: -740.615,
        warningInterval: 10,
        warningTime: '2024-02-05 00:18:24',
      },
      {
        componentId: null,
        componentName: '桥面铺装',
        createTime: null,
        firstWarningLower: -2,
        firstWarningUpper: 100000,
        handlerTime: null,
        handlerUserId: null,
        id: 898811,
        level: 3,
        machineId: null,
        measures: null,
        modifyTime: null,
        secondWarningLower: -1,
        secondWarningUpper: 80000,
        sendMessage: null,
        sensorCoding: 'C222201',
        sensorDetailsId: 7,
        sensorId: 1623,
        sensorName: '火车站-市区 车道1',
        sensorTypeName: '称重传感器',
        status: 0,
        structureId: 1578,
        structureName: '台江大桥',
        thirdWarningLower: 0,
        thirdWarningUpper: 50000,
        unit: 't',
        username: null,
        value: 55000,
        warningInterval: 1,
        warningTime: '2024-02-04 23:43:06',
      },
      {
        componentId: null,
        componentName: '桥面铺装',
        createTime: null,
        firstWarningLower: -2,
        firstWarningUpper: 100000,
        handlerTime: null,
        handlerUserId: null,
        id: 898810,
        level: 3,
        machineId: null,
        measures: null,
        modifyTime: null,
        secondWarningLower: -1,
        secondWarningUpper: 80000,
        sendMessage: null,
        sensorCoding: 'C222201',
        sensorDetailsId: 7,
        sensorId: 1623,
        sensorName: '火车站-市区 车道1',
        sensorTypeName: '称重传感器',
        status: 0,
        structureId: 1578,
        structureName: '台江大桥',
        thirdWarningLower: 0,
        thirdWarningUpper: 50000,
        unit: 't',
        username: null,
        value: 52290,
        warningInterval: 1,
        warningTime: '2024-02-04 23:39:25',
      },
      {
        componentId: null,
        componentName: '桥面铺装',
        createTime: null,
        firstWarningLower: -2,
        firstWarningUpper: 100000,
        handlerTime: null,
        handlerUserId: null,
        id: 898809,
        level: 3,
        machineId: null,
        measures: null,
        modifyTime: null,
        secondWarningLower: -1,
        secondWarningUpper: 80000,
        sendMessage: null,
        sensorCoding: 'C222202',
        sensorDetailsId: 7,
        sensorId: 1624,
        sensorName: '火车站-市区 车道2',
        sensorTypeName: '称重传感器',
        status: 0,
        structureId: 1578,
        structureName: '台江大桥',
        thirdWarningLower: 0,
        thirdWarningUpper: 50000,
        unit: 't',
        username: null,
        value: 54870,
        warningInterval: 1,
        warningTime: '2024-02-04 22:45:18',
      },
      {
        componentId: null,
        componentName: '桥面铺装',
        createTime: null,
        firstWarningLower: -2,
        firstWarningUpper: 100000,
        handlerTime: null,
        handlerUserId: null,
        id: 898808,
        level: 3,
        machineId: null,
        measures: null,
        modifyTime: null,
        secondWarningLower: -1,
        secondWarningUpper: 80000,
        sendMessage: null,
        sensorCoding: 'C222201',
        sensorDetailsId: 7,
        sensorId: 1623,
        sensorName: '火车站-市区 车道1',
        sensorTypeName: '称重传感器',
        status: 0,
        structureId: 1578,
        structureName: '台江大桥',
        thirdWarningLower: 0,
        thirdWarningUpper: 50000,
        unit: 't',
        username: null,
        value: 53390,
        warningInterval: 1,
        warningTime: '2024-02-04 22:02:33',
      },
    ],
    navigateFirstPage: 1,
    navigateLastPage: 8,
    navigatePages: 8,
    navigatepageNums: [1, 2, 3, 4, 5, 6, 7, 8],
    nextPage: 2,
    pageNum: 1,
    pageSize: 10,
    pages: 88111,
    prePage: 0,
    size: 10,
    startRow: 1,
    total: 881107,
  })

const tableFilter = [
  {
    label: '报告类型',
    name: 'structureName',
    component: 'Select',
    props: {
      options: [],
    },
  },
  {
    label: '项目',
    name: 'sensorName',
    component: 'Select',
  },
  {
    label: '关键字',
    name: 'level',
    component: 'Input',
  },
]

const tableOperates = [
  {
    name: '上传报告',
    type: 'primary',
    onClick: () => actions.onCreate(),
  },
]

const tableColumns = [
  {
    title: '报表名称',
    dataIndex: 'structureName',
    align: 'left',
  },
  {
    title: '项目名称',
    dataIndex: 'warningTime',
    align: 'center',
  },
  {
    title: '报表类型',
    dataIndex: 'sensorName',
    align: 'center',
  },
  {
    title: '上传人员',
    dataIndex: 'componentName',
    align: 'center',
  },
  {
    title: '上传时间',
    dataIndex: 'componentName',
    align: 'center',
  },
  {
    title: '操作',
    align: 'center',
    width: 200,
    render: ({ record }: any) => {
      return (
        <Space size={10}>
          <Link onClick={() => actions.onEdit(record)}>编辑</Link>
          <Link onClick={() => actions.onDownload(record)}>下载</Link>
          <Link onClick={() => actions.onDelete(record)}>删除</Link>
        </Space>
      )
    },
  },
]

const actions = {
  onCreate: async () => {
    // const result = await createBaseModal(ReportEditor, {
    //   mode: 'create',
    //   title: '上传报表',
    // })
    // result && refresh()
  },
  onEdit: async (record: any) => {
    // const result = await createBaseModal(ReportEditor, {
    //   mode: 'edit',
    //   title: '修改报表',
    //   record,
    // })
    // result && refresh()
  },
  onDelete: () => {},
  onDownload: () => {},
}
</script>
